# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Marc-André Véronneau
email: hello@maveronneau.com
description: >
  A full-stack designer from Montreal driven by innovation, and passionate about crafting beautiful, memorable and meaningful experiences.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://maveronneau.github.io" # the base hostname & protocol for your site
twitter_username: maveronneau
github_username:  maveronneau
dribbble_username: maveronneau

collections:
  project:
    output: true
    permalink: /project/:path/

# Build settings
markdown: kramdown
